import argparse
import sys
import random
from datetime import datetime, timedelta

parser = argparse.ArgumentParser(description="Script for creating time series data")

#start date, end date tick rate millis, outputfile

parser.add_argument(
'--start_date',
type=datetime.fromisoformat, 
dest='start_date', 
required=True,
help='start date for time series in ISO Format YYYY-MM-DD'
)

parser.add_argument(
'--end_date',
type=datetime.fromisoformat, 
dest='end_date', 
required=True,
help='end date for time series in ISO Format YYYY-MM-DD, last entry in series will be end date - tick rate'
)

parser.add_argument(
'--tick_rate',
type=int, 
dest='tick_rate', 
required=True,
help='rate at which values are produced in milli seconds'
)

parser.add_argument(
'--output_file',
type=str, 
dest='output', 
help='destination file for timeseries, if missing uses STDOUT'
)

parser.add_argument(
'--first_dimension',
type=str, 
dest='first_dimension',
required=True, 
help='first dimension for timeseries'
)

parser.add_argument(
'--start_value',
type=int, 
dest='start_value',
required=True, 
help='start_value for timeseries'
)

parser.add_argument(
'--delimiter',
type=str, 
dest='delimiter',
required=True, 
help='delimiter for output columns'
)

parser.add_argument(
'--offset',
type=int, 
dest='offset',
required=True, 
help='offset from shape values generated by random seed and start value'
)

parser.add_argument(
'--random_seed',
type=int, 
dest='random_seed',
required=True, 
help='python random will produce the same result for the same number and type of call'
)

args  = parser.parse_args()

random_seed = args.random_seed
start_date = args.start_date
end_date = args.end_date
tick_rate = args.tick_rate
delimiter = args.delimiter
dimension = args.first_dimension
current_value = args.start_value
offset = args.offset
output = sys.stdout if args.output is None else open(args.output + "_" + str(offset) + "_ts.csv",'w')
current_tick = start_date


random.seed(random_seed)

#will probably pull these out to a module/class, and assign variable number of arguments to the functions

shape_value = current_value

def get_next_shape_value(value):
    x = random.randint(-29,30)
    return (value + x)


def get_next_offset_value(value, offset):
    return value + offset


while (current_tick < end_date):
    output.write(f"{current_tick:%Y-%m-%d %H:%M:%S.%f}{delimiter}{dimension}{delimiter}{current_value}\n")
    current_tick = current_tick + timedelta(milliseconds=tick_rate)
    shape_value = get_next_shape_value(shape_value)
    current_value = get_next_offset_value(shape_value,offset)
